"""Assembles the final README.md from generated content and project metadata."""

from __future__ import annotations

from readme_ai.analyzer import ProjectInfo
from readme_ai.badges import generate_badges
from readme_ai.llm.base import GeneratedContent

WATERMARK = (
    "\n\n---\n\n"
    "<div align=\"center\">\n"
    "  <sub>README generated by <a href=\"https://github.com/yourusername/readme-ai\">readme-ai</a></sub>\n"
    "</div>\n"
)


class ReadmeBuilder:
    """Builds the final README.md string."""

    def __init__(self, project_info: ProjectInfo) -> None:
        self.info = project_info

    def build(self, content: GeneratedContent) -> str:
        sections: list[str] = []

        sections.append(self._header(content))
        sections.append(self._toc(content))
        sections.append(self._about(content))
        sections.append(self._features(content))
        sections.append(self._installation(content))
        sections.append(self._quick_start(content))

        if content.usage_examples:
            sections.append(self._usage(content))

        if content.api_overview:
            sections.append(self._api(content))

        if content.configuration or self.info.env_vars:
            sections.append(self._configuration(content))

        if content.roadmap:
            sections.append(self._roadmap(content))

        sections.append(self._contributing())
        sections.append(self._license())
        sections.append(WATERMARK)

        return "\n\n".join(s.strip() for s in sections if s.strip()) + "\n"

    # -------------------------------------------------------------------------
    # Section builders
    # -------------------------------------------------------------------------

    def _header(self, content: GeneratedContent) -> str:
        badges = generate_badges(self.info)
        tagline = content.tagline or f"A {self.info.language} project"
        return (
            f"<div align=\"center\">\n\n"
            f"# {self.info.name}\n\n"
            f"**{tagline}**\n\n"
            f"{badges}\n\n"
            f"</div>"
        )

    def _toc(self, content: GeneratedContent) -> str:
        links = [
            "- [About](#about)",
            "- [Features](#features)",
            "- [Installation](#installation)",
            "- [Quick Start](#quick-start)",
        ]
        if content.usage_examples:
            links.append("- [Usage](#usage)")
        if content.api_overview:
            links.append("- [API Reference](#api-reference)")
        if content.configuration or self.info.env_vars:
            links.append("- [Configuration](#configuration)")
        if content.roadmap:
            links.append("- [Roadmap](#roadmap)")
        links += [
            "- [Contributing](#contributing)",
            "- [License](#license)",
        ]
        return "## Table of Contents\n\n" + "\n".join(links)

    def _about(self, content: GeneratedContent) -> str:
        return f"## About\n\n{content.description}"

    def _features(self, content: GeneratedContent) -> str:
        if not content.features:
            return ""
        items = "\n".join(f"- {f}" for f in content.features)
        return f"## Features\n\n{items}"

    def _installation(self, content: GeneratedContent) -> str:
        body = content.installation or f"```bash\npip install {self.info.name}\n```"
        return f"## Installation\n\n{body}"

    def _quick_start(self, content: GeneratedContent) -> str:
        body = content.quick_start or "_No quick start available._"
        return f"## Quick Start\n\n{body}"

    def _usage(self, content: GeneratedContent) -> str:
        return f"## Usage\n\n{content.usage_examples}"

    def _api(self, content: GeneratedContent) -> str:
        return f"## API Reference\n\n{content.api_overview}"

    def _configuration(self, content: GeneratedContent) -> str:
        parts: list[str] = []

        if content.configuration:
            parts.append(content.configuration)

        if self.info.env_vars:
            rows = ["| Variable | Required | Description |", "|----------|----------|-------------|"]
            for var in self.info.env_vars:
                rows.append(f"| `{var}` | — | — |")
            parts.append("### Environment Variables\n\n" + "\n".join(rows))

        return "## Configuration\n\n" + "\n\n".join(parts)

    def _roadmap(self, content: GeneratedContent) -> str:
        items = "\n".join(f"- [ ] {item}" for item in content.roadmap)
        return f"## Roadmap\n\n{items}"

    def _contributing(self) -> str:
        repo = self.info.repo_url or "https://github.com/yourusername/yourrepo"
        return f"""\
## Contributing

Contributions are welcome! Please read [CONTRIBUTING.md](CONTRIBUTING.md) for guidelines.

1. Fork the repository
2. Create a feature branch (`git checkout -b feature/amazing-feature`)
3. Commit your changes (`git commit -m 'Add amazing feature'`)
4. Push to the branch (`git push origin feature/amazing-feature`)
5. Open a Pull Request

Found a bug or have a feature request? [Open an issue]({repo}/issues)."""

    def _license(self) -> str:
        license_type = self.info.license_type or "MIT"
        return f"## License\n\nThis project is licensed under the [{license_type} License](LICENSE)."
